<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Code_companycode</name>
   <tag></tag>
   <elementGuidId>b0ac1578-4045-4e94-aba2-f2c290581496</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-companycode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-companycode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cec3ab24-7a46-41c8-8bfe-c870bbeae17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>472b10ad-d671-4798-baaa-4dff88e8bbf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-companycode</value>
      <webElementGuid>2f05a162-599b-456a-a0ef-00f09a7a10a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>companycode</value>
      <webElementGuid>07b8492e-7fa5-4eb4-ba4b-f6782c1fd59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>3e2cbf33-aa28-4160-8a27-7ab42a95fa7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-full-width input-md input-rectangle ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>8fc97e17-c809-452f-a28a-a7271a810f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-companycode&quot;)</value>
      <webElementGuid>711bb9dd-b578-4fe7-88d8-4ca5a89270d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-companycode']</value>
      <webElementGuid>a59a2bd8-c48f-4ea3-84ea-a3547df779ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>05b4a471-33a5-4632-88fd-91c58cc92ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-companycode' and @name = 'companycode' and @placeholder = 'Code']</value>
      <webElementGuid>b15f3707-88f6-4a5f-af2b-5b08896d9073</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
