<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Limit Paylater_selectedLimitPaylater</name>
   <tag></tag>
   <elementGuidId>8b1bf3e9-e688-4506-b27e-4505b904b9cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectedLimitPaylater</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectedLimitPaylater']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2f75f67-93f8-46e2-9de8-1e7dfd1d5fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b8c2363c-5235-4422-bfe8-df2747f4d8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedLimitPaylater</value>
      <webElementGuid>fd3e0bc0-330c-4376-9d8e-86f79718474f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>084e2146-0037-490e-aca2-156300f6d828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedLimitPaylater&quot;)</value>
      <webElementGuid>f371da83-c4a4-4c3f-a2b6-538551295dc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectedLimitPaylater']</value>
      <webElementGuid>7a3c4a13-dc4c-4df6-aec6-4396d3cb63f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/input</value>
      <webElementGuid>4737590e-1d52-4d99-a850-2ec3432e339c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'selectedLimitPaylater' and @type = 'number']</value>
      <webElementGuid>77dd721b-5dd7-4b0e-98f4-5f1fa4fb3372</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
