<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Simpanan Mobile - Anggota Koperasi</name>
   <tag></tag>
   <elementGuidId>8734537b-d590-46da-9bbe-860ae8318469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='adcdc0865b3f-0']/div/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = ' Simpanan Mobile - Anggota Koperasi ' or . = ' Simpanan Mobile - Anggota Koperasi ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5e6d2c7b-fbf0-4e51-8251-8ee43fcd8ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-cell</value>
      <webElementGuid>9d582e39-1344-490f-b34b-59f03c6f7757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Simpanan Mobile - Anggota Koperasi </value>
      <webElementGuid>04892db0-7ac3-441a-851c-ef4d87569655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adcdc0865b3f-0&quot;)/div[@class=&quot;table-row ng-star-inserted&quot;]/div[@class=&quot;table-cell&quot;]</value>
      <webElementGuid>e50a05fa-3c6a-4427-999f-d232ca077fdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adcdc0865b3f-0']/div/div[2]</value>
      <webElementGuid>ef1914c7-cacd-4cd2-840a-59095d0eb980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary Account'])[1]/following::div[11]</value>
      <webElementGuid>41d4397c-7a02-4432-a3d3-37ded8a99841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grade'])[1]/following::div[13]</value>
      <webElementGuid>0202193d-ac9b-4c99-80e0-8b24b058329b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::div[1]</value>
      <webElementGuid>8fec252b-be10-4289-b86e-c6f786a651ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[11]</value>
      <webElementGuid>7a6a2ea6-f59a-41cd-b410-26166ddb6169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpanan Mobile - Anggota Koperasi']/parent::*</value>
      <webElementGuid>d8393791-fa33-435a-b8d0-c38a97a9517a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]</value>
      <webElementGuid>0cb8a31a-67d7-496c-bfdb-1df8f76ef44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Simpanan Mobile - Anggota Koperasi ' or . = ' Simpanan Mobile - Anggota Koperasi ')]</value>
      <webElementGuid>659b05c6-e236-4d69-847b-4e6f7a3463e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
