<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode Member_cif</name>
   <tag></tag>
   <elementGuidId>dd0b054a-c2a7-4cbc-852c-dfcc6329ccb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cif</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cif']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc23f68e-86c6-4b88-ac0f-620013121790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b95d306a-c2f2-47b8-9bb7-76611df32cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cif</value>
      <webElementGuid>9dae6d05-080c-4a3a-ab9f-f604cf504a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Kode Member disini</value>
      <webElementGuid>c1d9a210-131a-4f14-8266-82d8b0ba1e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f50f570-8ac1-4cf2-bd5a-df35be9cde53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cif&quot;)</value>
      <webElementGuid>150aea4c-437c-4f9f-b345-5444eac95587</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cif']</value>
      <webElementGuid>1e69355b-1ddc-4a4a-ba4f-086c277a4e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>e7b03255-7c73-421a-bf1f-9eff99e0be60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cif' and @placeholder = 'Input Kode Member disini' and @type = 'text']</value>
      <webElementGuid>0dd830fa-6767-4845-a45a-ab01dca41114</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
