<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>31d305fa-1f15-4b52-89d9-ddb121879ae3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#blockui_sample_2_1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'javascript:;' and @id = 'blockui_sample_2_1' and (text() = '
                                                         Logout
                                                    ' or . = '
                                                         Logout
                                                    ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='blockui_sample_2_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70448c41-899e-4dc2-8fd8-9ec72b653d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>cac74baa-d210-4e53-928e-e30bbc9f92d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return logout('ApiCardlez', '420b7409-18e5-4a8b-ba36-4f9a650ccf3d', '00000000-0000-0000-0000-000000001001')</value>
      <webElementGuid>3b37a9b0-a530-4646-8ce2-e95ce2f794ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn default btn-xs purple</value>
      <webElementGuid>bad90188-c8c8-4cf0-9a1b-355e50beb820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>blockui_sample_2_1</value>
      <webElementGuid>2a88b45d-55b8-4ce7-b999-1adda2def296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                         Logout
                                                    </value>
      <webElementGuid>66165e17-b79a-412f-a84a-b1b958b0d598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blockui_sample_2_1&quot;)</value>
      <webElementGuid>834efe3f-4511-45f5-b957-2264772423e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='blockui_sample_2_1']</value>
      <webElementGuid>4261995c-1ebf-41b6-b485-7d2db4c772cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='sample_6']/tbody/tr/td[3]/a</value>
      <webElementGuid>f63046be-34cc-45ca-99b5-0cba560d5e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ApiCardlez'])[1]/following::a[1]</value>
      <webElementGuid>a2e965ab-a5da-4409-a3b6-427fa783c53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logged Time'])[1]/following::a[1]</value>
      <webElementGuid>f0871dfd-af17-4793-a968-66e3d290b194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Root'])[2]/preceding::a[1]</value>
      <webElementGuid>698a60bf-589e-44c4-955a-51ff977271ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>a2d2c3e9-6763-4e21-9040-542b7ff4d4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[55]</value>
      <webElementGuid>5c06148f-9ea4-49c9-9081-81b9867a5ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>5d759ea5-765a-438e-b10d-ad9bc518795c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and @id = 'blockui_sample_2_1' and (text() = '
                                                         Logout
                                                    ' or . = '
                                                         Logout
                                                    ')]</value>
      <webElementGuid>b15c3087-7009-415d-b5dc-3bb7bf604b70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
