<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_End Of Day</name>
   <tag></tag>
   <elementGuidId>e9ea015b-ed5b-4916-8663-75295e6ed5a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnendofday</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnendofday']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68f58c3f-2915-4608-b5bd-580d26888286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c14ac15c-64e7-491c-b09d-143f6289495b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn blue</value>
      <webElementGuid>105cb2aa-da0d-4b83-8185-161363c5e16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnendofday</value>
      <webElementGuid>9900addd-05af-4e8c-b099-c883cffd4dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>EndOfDay()</value>
      <webElementGuid>2d747968-1883-4416-b6b1-8719bd16c7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>End Of Day</value>
      <webElementGuid>32a979d4-4cba-4b86-ad7b-e1e6af5f410d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnendofday&quot;)</value>
      <webElementGuid>1675e48b-d60d-4f3e-afa3-b0224c40798b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnendofday']</value>
      <webElementGuid>70476335-650a-4942-8c54-9032fbe4854a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='eodform']/div/div[3]/div/div/button</value>
      <webElementGuid>4e13b732-4e4f-4cba-9f19-d29063babf9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Root'])[2]/following::button[1]</value>
      <webElementGuid>34ba2374-3c0e-4fc1-ab48-35cd6109341a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logged Time'])[1]/following::button[1]</value>
      <webElementGuid>afb36d0a-bcfe-4f5a-9669-86696d6d7281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2f04628f-e2b8-44c6-9e9b-e98434ec43a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnendofday' and (text() = 'End Of Day' or . = 'End Of Day')]</value>
      <webElementGuid>5abc20bf-4e19-4391-9415-9f68b918dd80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
