<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Actions_form-control ng-untouched ng-_a2d6c4</name>
   <tag></tag>
   <elementGuidId>91c32e9a-16e2-45f7-a77a-59546253b5ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.ng2-smart-th.handphone.ng-star-inserted > ng2-smart-table-filter > div.ng2-smart-filter.ng-star-inserted > default-table-filter.ng-star-inserted > input-filter.ng-star-inserted > input.form-control.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c010eb1b-52f8-41eb-b815-9521485ee22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>241d8311-1882-47e5-9f45-a3e6557cbe88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>102b4bb7-fca9-4930-9637-b4390461fee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>cb47499c-2820-48b6-a657-c7a7d932581f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;nb-theme-default    pace-done&quot;]/ngx-app[1]/ngx-pages[1]/ngx-sample-layout[1]/nb-layout[@class=&quot;window-mode with-scroll&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/nb-layout-column[@class=&quot;main-content&quot;]/ngx-member[@class=&quot;ng-star-inserted&quot;]/ngx-approval-existing-member[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-12&quot;]/nb-card[1]/nb-card-body[1]/ng2-smart-table[1]/table[1]/thead[@class=&quot;ng-star-inserted&quot;]/tr[@class=&quot;ng2-smart-filters ng-star-inserted&quot;]/th[@class=&quot;ng2-smart-th handphone ng-star-inserted&quot;]/ng2-smart-table-filter[1]/div[@class=&quot;ng2-smart-filter ng-star-inserted&quot;]/default-table-filter[@class=&quot;ng-star-inserted&quot;]/input-filter[@class=&quot;ng-star-inserted&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>a3f0879f-8edd-42a4-928d-10d168cde726</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>ba3b6923-3e17-4153-ae23-2695de370c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/ng2-smart-table-filter/div/default-table-filter/input-filter/input</value>
      <webElementGuid>a6b0d566-0e63-41dc-aa2b-37cd071e0dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Phone']</value>
      <webElementGuid>378d4ef8-79ee-40b9-b929-9896afa5e59a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
