<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RTRW_txtRW</name>
   <tag></tag>
   <elementGuidId>3ededc9e-dd95-40b2-9eda-6764411a145d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtRW</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtRW']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecdb6115-447f-44fb-96c8-3c552543c834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55b7994e-d39d-47a3-92d5-d64112698c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6085f71f-eeaa-4dfa-9e69-f15332b65acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtRW</value>
      <webElementGuid>75b4e25c-cdd5-4249-a9e0-ce9edfed0dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>22e32859-8183-4074-86c8-f84d276ffc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtRW&quot;)</value>
      <webElementGuid>ffeeb48f-b268-4b21-8c50-14f7bb84338a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtRW']</value>
      <webElementGuid>9b523647-4569-406b-a7ae-cac2f39c07ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[5]/div[2]/input</value>
      <webElementGuid>099abb71-0b42-43ff-8fd4-d815e1d5850a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[5]/div[2]/input</value>
      <webElementGuid>89e33f13-2d63-4a8b-8c2d-ddefeb15fd4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtRW']</value>
      <webElementGuid>0e9a8125-7925-4a8d-b566-6e4f05c9bbb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
