<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Ibu Kandung_MotherMaiden</name>
   <tag></tag>
   <elementGuidId>afe83ae9-b8b0-4acb-8825-d325980a0a54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MotherMaiden</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MotherMaiden']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>005b282a-2504-4326-a86a-755159ef2cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-circle</value>
      <webElementGuid>01590c9f-1a36-4b75-90de-9a3609194df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MotherMaiden</value>
      <webElementGuid>dbfe9046-0056-48f3-8efe-14b6793af78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MotherMaiden</value>
      <webElementGuid>6fbd362b-e66e-4ac8-9e46-671cfa34415a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b0f7ba3-2ea8-4504-ac72-4552b265f582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return /^[a-zA-Z\s]*$/.test(event.key)</value>
      <webElementGuid>ec904261-6906-4ebc-bc7b-a722dfc7008c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MotherMaiden&quot;)</value>
      <webElementGuid>d3c201b1-885c-456a-a0b9-f2c9eb041d28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MotherMaiden']</value>
      <webElementGuid>8e34c053-44f1-4c60-bc7c-18634b84672d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ibukandung']/div/input</value>
      <webElementGuid>08dd439b-6aa7-40fa-9288-fac681c9f208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/input</value>
      <webElementGuid>b466f286-9e91-4bee-b1f0-8affe5e7c48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MotherMaiden' and @name = 'MotherMaiden' and @type = 'text']</value>
      <webElementGuid>e03fb960-cccb-45f5-9e6b-8738e08083f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
