<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Telepon 1_No_Tlp</name>
   <tag></tag>
   <elementGuidId>cd39f396-905b-44fe-8aeb-76023b1a806d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#No_Tlp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='No_Tlp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d9ec2d9-4184-41c8-aae9-b446b32af577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-circle</value>
      <webElementGuid>c3facfee-80fd-4957-8404-1b7b4c7ee494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>No_Tlp</value>
      <webElementGuid>1af3a3d9-8200-40f4-9f8d-05d36e5209b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>No_Tlp</value>
      <webElementGuid>aedda1af-3e30-419f-b0e3-a4875c7eaef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8abaa49f-f53a-469f-b050-41b773e79f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*?)\..*/g, '$1');</value>
      <webElementGuid>fdfe54d8-2836-4e83-84b9-7d790a66ea76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;No_Tlp&quot;)</value>
      <webElementGuid>d6f9e49d-a7fb-4d6d-9476-052e058ca325</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='No_Tlp']</value>
      <webElementGuid>5ab532e1-3449-4df3-b95a-e65c3f5908ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div[8]/div/input</value>
      <webElementGuid>b21c1869-3072-45ba-a3b5-b2a8b51f0ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>1dd02c15-ec87-4c58-8cba-5239994123f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'No_Tlp' and @name = 'No_Tlp' and @type = 'text']</value>
      <webElementGuid>40c456b1-9b98-44b5-be15-688870cb69da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
