<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Identitas_NoKtp</name>
   <tag></tag>
   <elementGuidId>4fabeb02-1cb5-415a-957c-8a300ee254cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NoKtp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NoKtp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2b3b8aa-e2fd-47e1-a56b-798dc4e71684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-circle</value>
      <webElementGuid>42a707e6-5878-4830-af65-08aa7f28bb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NoKtp</value>
      <webElementGuid>f04cf1ce-3715-4194-a736-9a0053822524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NoKtp</value>
      <webElementGuid>53a222ac-63df-4457-90da-b9e4f3d861d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f37cd31-2503-47cd-aa36-3d8813e39736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*?)\..*/g, '$1');</value>
      <webElementGuid>44d168a3-a998-499d-abc5-bee7c2878fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NoKtp&quot;)</value>
      <webElementGuid>06f6df17-117e-4655-8647-e729e984403c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NoKtp']</value>
      <webElementGuid>381c2834-5d17-4282-ac4a-e6f5631e9304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div[5]/div[2]/input</value>
      <webElementGuid>dd26a07b-0327-489c-829b-d650ce5c0c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[5]/div[2]/input</value>
      <webElementGuid>523c7eef-080e-40f6-aa32-71086b1aee54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NoKtp' and @name = 'NoKtp' and @type = 'text']</value>
      <webElementGuid>f6576d20-4e74-4d6e-8111-9913bd5b824d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
