<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RTRW_txtRT</name>
   <tag></tag>
   <elementGuidId>00d1c882-0f19-4ff1-879c-2edb95a13c37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtRT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtRT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24a5e6db-a957-458f-98db-4037f1c781f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f61122ae-6c53-4152-8833-3e74be5ce715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2413bb33-da51-4a80-bc15-a01272435705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtRT</value>
      <webElementGuid>ec8f0a05-becf-4f60-aaf8-520ec2f88cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>690f33d7-c4fc-404d-b286-ef079c0ea792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtRT&quot;)</value>
      <webElementGuid>2ad31415-1be1-4359-a43c-afc6e0166b43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtRT']</value>
      <webElementGuid>478d90c3-3d1f-49f1-8769-e5b9ae8fbc9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[5]/div/input</value>
      <webElementGuid>6371dd6c-51e4-453f-91fc-ab4c7ee50084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[5]/div/input</value>
      <webElementGuid>2720ec63-b7e8-4473-85d4-37ae2c741b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtRT']</value>
      <webElementGuid>a8840650-ba75-44b8-a445-aa3721369372</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
