<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Kecamatan --Bogor Tengah - KotaTa_c549b7</name>
   <tag></tag>
   <elementGuidId>cb4a4211-53c6-4d61-bc58-6cbe6aa81575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtsubdistrict</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='txtsubdistrict']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c33fd005-6e53-4740-afa9-6ca0e379c321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-circle</value>
      <webElementGuid>3c588b29-38d5-4f86-8d12-1be023130eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1bfae1a9-47f6-4431-860e-399ee8cc8704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Guid field is required.</value>
      <webElementGuid>970fc0bd-85c6-4ead-a134-ed8d699455b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtsubdistrict</value>
      <webElementGuid>c4229c36-d763-40d2-9791-595458f53d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtsubdistrict</value>
      <webElementGuid>00ba2cbd-d0ac-46c2-9cd3-682d4ae3b7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ajax_kecamatanalamat()</value>
      <webElementGuid>83e289ad-c7b1-42fa-b3bf-8e39ad40a56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Kecamatan --Bogor Tengah - KotaTanah SerealBogor Selatan - KotaBogor Barat - KotaBogor Timur - KotaBogor Utara - Kota</value>
      <webElementGuid>a00fd3a4-8656-40d0-b004-03389ede8ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtsubdistrict&quot;)</value>
      <webElementGuid>31897873-c4c9-455a-8edd-63ebd5230bde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='txtsubdistrict']</value>
      <webElementGuid>cf9b4453-3028-4a90-8048-640360b57cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[2]/div[2]/select</value>
      <webElementGuid>b22d9694-70c3-48cf-981f-e748f93effaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[2]/following::select[1]</value>
      <webElementGuid>259058b8-7a2d-45a9-a8e5-f01250c2c6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten/Kota Lokasi Dati II'])[1]/following::select[2]</value>
      <webElementGuid>5f251394-b660-4f97-81d6-075d44242ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan'])[1]/preceding::select[1]</value>
      <webElementGuid>25f71cad-5ad3-45a5-a667-9bffce77a7b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[1]/preceding::select[2]</value>
      <webElementGuid>77b799bb-801e-40b0-8485-a983560480d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/select</value>
      <webElementGuid>30b33fec-6db3-4d3d-94f0-9420f1dce284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'txtsubdistrict' and @name = 'txtsubdistrict' and (text() = '-- Kecamatan --Bogor Tengah - KotaTanah SerealBogor Selatan - KotaBogor Barat - KotaBogor Timur - KotaBogor Utara - Kota' or . = '-- Kecamatan --Bogor Tengah - KotaTanah SerealBogor Selatan - KotaBogor Barat - KotaBogor Timur - KotaBogor Utara - Kota')]</value>
      <webElementGuid>78beb9c8-1deb-4d4b-a9a7-f6ce7ef68c1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
