<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Kelurahan --EmpangBatutulisCipaku_174451</name>
   <tag></tag>
   <elementGuidId>dca34b2f-5335-49cc-bd15-7580b4900376</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtMunicipalityalamat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='txtMunicipalityalamat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a4e7dac7-8044-4cce-b8f7-35562a4a8087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-circle</value>
      <webElementGuid>69b56624-d394-44e4-99dd-f46b58d0130e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9d1a862f-03c9-4066-898e-67d01263fa81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Guid field is required.</value>
      <webElementGuid>4c63c77e-10c5-4116-8c2a-c75f48d9ec65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMunicipalityalamat</value>
      <webElementGuid>771914c7-d618-45a5-85d1-f7a59d0eaa14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtMunicipalityalamat</value>
      <webElementGuid>79e422f2-db81-4873-853a-a56630617318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ajax_kodepos()</value>
      <webElementGuid>196162cc-a087-4874-a7ab-0c352b5741c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Kelurahan --EmpangBatutulisCipakuPakuanPamoyananRancamayaBondonganBojongkertaRanggamekarMulyaharjaGentengMuarasariLawang GintungKertamayaCikaretHarjasari</value>
      <webElementGuid>8bd68e70-4c07-4b23-a426-4a1073f6a3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMunicipalityalamat&quot;)</value>
      <webElementGuid>e17aeeb7-428d-4d22-b50d-10135798e8c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='txtMunicipalityalamat']</value>
      <webElementGuid>e61bc720-56db-4f43-9094-3e638e7e18e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[4]/div/select</value>
      <webElementGuid>7f1c0347-0ae0-471a-83d2-5d9562ae07d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan'])[1]/following::select[1]</value>
      <webElementGuid>508c8c8c-8004-4c53-9b2c-da50b1b890cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[2]/following::select[2]</value>
      <webElementGuid>93e66bd1-73a3-4b1c-b9b6-97d07049962a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[1]/preceding::select[1]</value>
      <webElementGuid>fc84ac8b-9b0b-4a1c-9584-fa99e284b357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RT/RW'])[1]/preceding::select[1]</value>
      <webElementGuid>fafd5c44-da7e-42af-996c-7a2865e6202c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/div/select</value>
      <webElementGuid>6f4ba19a-2992-43db-8527-8312a2348bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'txtMunicipalityalamat' and @name = 'txtMunicipalityalamat' and (text() = '-- Kelurahan --EmpangBatutulisCipakuPakuanPamoyananRancamayaBondonganBojongkertaRanggamekarMulyaharjaGentengMuarasariLawang GintungKertamayaCikaretHarjasari' or . = '-- Kelurahan --EmpangBatutulisCipakuPakuanPamoyananRancamayaBondonganBojongkertaRanggamekarMulyaharjaGentengMuarasariLawang GintungKertamayaCikaretHarjasari')]</value>
      <webElementGuid>18cbaf0f-0998-4d7d-be76-6c913388ca53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
