<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Kota --Bandung Barat, Kab.Bandung_45be65</name>
   <tag></tag>
   <elementGuidId>a77917f5-ad8f-4c39-9046-740709adb310</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtDistrict</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='txtDistrict']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f24489c4-bfaf-4880-965e-e6a4e6948966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-circle</value>
      <webElementGuid>2c72fd40-963a-4762-a4cd-696a57fc1d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d98c504c-8a68-43e2-a506-b0071bcda8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Guid field is required.</value>
      <webElementGuid>0daac639-57a5-4e8b-a6cc-e0d94e06acb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtDistrict</value>
      <webElementGuid>04c98bf8-d6c5-4963-9ea6-d5b8990b5602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtDistrict</value>
      <webElementGuid>65db092b-7a93-4526-ba15-d5cbc302aad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ajax_kotaalamat()</value>
      <webElementGuid>383f1a35-57e1-48fd-85af-61b3cd138e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Kota --Bandung Barat, Kab.Bandung, Kab.Bandung, Kota.Banjar, Kota.Bekasi, Kab.Bekasi, Kota.Bogor, Kab.Bogor, Kota.Ciamis, Kab.Cianjur, Kab.Cimahi, Kota.Cirebon, Kab.Cirebon, Kota.Depok, Kota.Garut, Kab.Indramayu, Kab.Karawang, Kab.Kuningan, Kab.Majalengka, Kab.Prov. Jawa Barat, Kab./Kota Lainnya.Purwakarta, Kab.Subang, Kab.Sukabumi, Kab.Sukabumi, Kota.Sumedang, Kab.Tasikmalaya, Kab.Tasikmalaya, Kota.Pangandaran, Kab.</value>
      <webElementGuid>1b719d93-8e59-4f00-9b47-e52b98573638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtDistrict&quot;)</value>
      <webElementGuid>be919f76-e2c6-44e2-840d-98e7e100732d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='txtDistrict']</value>
      <webElementGuid>d26b4e04-925a-43b6-b0a5-b4f20b6332cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab2']/div[2]/div/select</value>
      <webElementGuid>19201989-9a71-4a70-a38f-c0159cd8e3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten/Kota Lokasi Dati II'])[1]/following::select[1]</value>
      <webElementGuid>2944ec77-dad5-47b1-8db3-431fb4712eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[2]</value>
      <webElementGuid>43c58019-598a-48ca-9071-35aad89daf3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan'])[2]/preceding::select[1]</value>
      <webElementGuid>f38ec605-a2e7-45fa-9c8a-175cb59a8750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kelurahan'])[1]/preceding::select[2]</value>
      <webElementGuid>9d807659-15ce-436b-a182-5fdfcc66164a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/select</value>
      <webElementGuid>2b3ed264-ced0-42fd-a59b-6499c6e68cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'txtDistrict' and @name = 'txtDistrict' and (text() = '-- Kota --Bandung Barat, Kab.Bandung, Kab.Bandung, Kota.Banjar, Kota.Bekasi, Kab.Bekasi, Kota.Bogor, Kab.Bogor, Kota.Ciamis, Kab.Cianjur, Kab.Cimahi, Kota.Cirebon, Kab.Cirebon, Kota.Depok, Kota.Garut, Kab.Indramayu, Kab.Karawang, Kab.Kuningan, Kab.Majalengka, Kab.Prov. Jawa Barat, Kab./Kota Lainnya.Purwakarta, Kab.Subang, Kab.Sukabumi, Kab.Sukabumi, Kota.Sumedang, Kab.Tasikmalaya, Kab.Tasikmalaya, Kota.Pangandaran, Kab.' or . = '-- Kota --Bandung Barat, Kab.Bandung, Kab.Bandung, Kota.Banjar, Kota.Bekasi, Kab.Bekasi, Kota.Bogor, Kab.Bogor, Kota.Ciamis, Kab.Cianjur, Kab.Cimahi, Kota.Cirebon, Kab.Cirebon, Kota.Depok, Kota.Garut, Kab.Indramayu, Kab.Karawang, Kab.Kuningan, Kab.Majalengka, Kab.Prov. Jawa Barat, Kab./Kota Lainnya.Purwakarta, Kab.Subang, Kab.Sukabumi, Kab.Sukabumi, Kota.Sumedang, Kab.Tasikmalaya, Kab.Tasikmalaya, Kota.Pangandaran, Kab.')]</value>
      <webElementGuid>9c7eeff0-0ec8-4995-91bd-a15c5c418907</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
