<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Akhir_datefinish</name>
   <tag></tag>
   <elementGuidId>d940f123-7e23-4480-be8c-0aafdb10a57d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datefinish']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#datefinish</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91806193-c9e6-4377-a60f-105a8ddf7bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-inline input-medium date-picker</value>
      <webElementGuid>b377caf2-38ec-4785-927d-ce01e7c94b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datefinish</value>
      <webElementGuid>85c40475-9ff0-4cd1-a859-7b389a1b02a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datefinish</value>
      <webElementGuid>6013e19a-e290-4d98-aaf8-d8d184601219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$(this).datepicker('show')</value>
      <webElementGuid>88276e63-96f9-4e0d-afa1-2a9cb59ae532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eacdfa9f-c379-45f5-8de3-2a63bf1544c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>27/07/2023</value>
      <webElementGuid>0657cdfe-cef6-46af-98b4-ac146fbe7886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datefinish&quot;)</value>
      <webElementGuid>aa80d659-c671-4f87-b753-dd02b9b488d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datefinish']</value>
      <webElementGuid>3d19bee9-560a-4985-949c-978cdd55fe70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchformview']/div/div/div[2]/div/input</value>
      <webElementGuid>e29dcfe2-8309-4f50-8293-c6bf2e695ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9354f47d-23c6-4913-b722-4c732fb4b9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'datefinish' and @name = 'datefinish' and @type = 'text']</value>
      <webElementGuid>845ebb55-1d44-49d2-b331-fd8588bf897e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
