<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Awal_datestart</name>
   <tag></tag>
   <elementGuidId>2b41e5a3-6ed7-4382-bca1-6bb3dc3731e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datestart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#datestart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cc68603-5a11-43f2-9f1e-8cbb42b32d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-inline input-medium date-picker</value>
      <webElementGuid>e4065c4a-caed-4d08-858f-6653c0ac7382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datestart</value>
      <webElementGuid>20559405-79b0-46be-af96-089376be2fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datestart</value>
      <webElementGuid>0e861769-5901-4c6e-b4e0-9fa92e5512ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$(this).datepicker('show')</value>
      <webElementGuid>28e0f51a-7a94-48aa-8e57-9b64c09b8b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d30131a-7cbf-4d10-9e81-504903f0a885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>27/07/2023</value>
      <webElementGuid>a9733923-2f7c-42d1-ab92-d73d79363d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datestart&quot;)</value>
      <webElementGuid>e7fa48e1-cde6-4650-a6b9-7276153a3894</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datestart']</value>
      <webElementGuid>ebc513d3-72f8-411c-a5c1-073f5d37c3ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchformview']/div/div/div/div/input</value>
      <webElementGuid>ab352cf3-b357-48dc-bc77-ed98d7364828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/input</value>
      <webElementGuid>ca6b06ab-8709-4388-a595-e3ad062c10c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'datestart' and @name = 'datestart' and @type = 'text']</value>
      <webElementGuid>0ea4fad0-aac4-404d-9928-ac5d5426dbfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
