<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Actions_form-control ng-untouched ng-_a2d6c4</name>
   <tag></tag>
   <elementGuidId>b36a98c0-4e20-4c76-879b-209b27bcd596</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>th.ng2-smart-th.accountCode.ng-star-inserted > ng2-smart-table-filter > div.ng2-smart-filter.ng-star-inserted > default-table-filter.ng-star-inserted > input-filter.ng-star-inserted > input.form-control.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ccae8ef4-dc83-4c10-8c88-2021d0b7ef2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>4032757d-e384-4e96-b124-ccf9a21f57f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4d233c8-d482-46a0-8411-ace2ac913069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rekening Sumber</value>
      <webElementGuid>b8201ec7-9d8d-4d57-844e-b1a6d6fb6776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;nb-theme-default    pace-done&quot;]/ngx-app[1]/ngx-pages[1]/ngx-sample-layout[1]/nb-layout[@class=&quot;window-mode with-scroll&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/nb-layout-column[@class=&quot;main-content&quot;]/ngx-tools[@class=&quot;ng-star-inserted&quot;]/ngx-approvaltransfer[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-12&quot;]/nb-card[1]/nb-card-body[1]/ng2-smart-table[1]/table[1]/thead[@class=&quot;ng-star-inserted&quot;]/tr[@class=&quot;ng2-smart-filters ng-star-inserted&quot;]/th[@class=&quot;ng2-smart-th accountCode ng-star-inserted&quot;]/ng2-smart-table-filter[1]/div[@class=&quot;ng2-smart-filter ng-star-inserted&quot;]/default-table-filter[@class=&quot;ng-star-inserted&quot;]/input-filter[@class=&quot;ng-star-inserted&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>e574249f-3e16-4058-abc1-63061457f59f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
      <webElementGuid>5f7c7edc-dbd3-4848-a8b3-bddfc8a00ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/ng2-smart-table-filter/div/default-table-filter/input-filter/input</value>
      <webElementGuid>07887444-2cf0-4e47-a103-0bfb855fac53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Rekening Sumber']</value>
      <webElementGuid>ea8570a5-2196-4f8b-91f7-bc8a53ba7248</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
