<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Actions_nb-edit</name>
   <tag></tag>
   <elementGuidId>e5dcd2fc-097f-44f9-b776-3520e4079627</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.nb-edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng2-st-tbody-edit-delete/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>68efc91c-47b4-4e6e-86ea-cff21f99c8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb-edit</value>
      <webElementGuid>57e2d5cb-65c7-4cc9-b8e4-0ecfa16e7ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;nb-theme-default    pace-done&quot;]/ngx-app[1]/ngx-pages[1]/ngx-sample-layout[1]/nb-layout[@class=&quot;window-mode with-scroll&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/nb-layout-column[@class=&quot;main-content&quot;]/ngx-master[@class=&quot;ng-star-inserted&quot;]/ngx-limit-transfer[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-12&quot;]/nb-card[1]/nb-card-body[1]/ng2-smart-table[1]/table[1]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;ng2-smart-actions ng-star-inserted&quot;]/ng2-st-tbody-edit-delete[1]/a[@class=&quot;ng2-smart-action ng2-smart-action-edit-edit ng-star-inserted&quot;]/i[@class=&quot;nb-edit&quot;]</value>
      <webElementGuid>cb8cae92-3588-4e3f-9896-5d28d7b84ac6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng2-st-tbody-edit-delete/a/i</value>
      <webElementGuid>2ec42623-4674-4690-9b8a-dcdba1cb6fbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
