<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Maksimal Nominal Transfer_transferMaxAmount</name>
   <tag></tag>
   <elementGuidId>4881e648-63a7-4c2f-a5f6-abe933aaa7a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transferMaxAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transferMaxAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6f68b88-24a6-4e3b-91b0-4b7c6094f479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>6147a268-1a9d-4c77-a1e5-7a85f8d5cb58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transferMaxAmount</value>
      <webElementGuid>a5eab677-88ec-41a4-98c5-c36335e7803e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e0bb449e-0956-4749-8a2a-2d17309d7642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transferMaxAmount&quot;)</value>
      <webElementGuid>4f15d8be-3d2f-4743-a387-52a5c05a54ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transferMaxAmount']</value>
      <webElementGuid>2d656358-2eb4-4121-97b0-626478edbbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>5e7e04f4-b044-41e4-9e6a-d6149bab1112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'transferMaxAmount' and @type = 'number']</value>
      <webElementGuid>a79ea880-0e9f-4151-a356-4d251dd2a718</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
