<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_isTransferAuthorJob_nb-edit</name>
   <tag></tag>
   <elementGuidId>b2f40869-8251-4757-ae38-c6eb2af549f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td/ng2-st-tbody-edit-delete/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>957e8aad-6978-437c-898c-cc8379f53913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb-edit</value>
      <webElementGuid>3111566c-ab7e-4d24-bf54-e78442536b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;nb-theme-default    pace-done&quot;]/ngx-app[1]/ngx-pages[1]/ngx-sample-layout[1]/nb-layout[@class=&quot;window-mode with-scroll&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/nb-layout-column[@class=&quot;main-content&quot;]/ngx-master[@class=&quot;ng-star-inserted&quot;]/ngx-application-configuration[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/nb-card[1]/nb-card-body[1]/ng2-smart-table[1]/table[1]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;ng2-smart-actions ng-star-inserted&quot;]/ng2-st-tbody-edit-delete[1]/a[@class=&quot;ng2-smart-action ng2-smart-action-edit-edit ng-star-inserted&quot;]/i[@class=&quot;nb-edit&quot;]</value>
      <webElementGuid>b12c3f44-ce86-4c3a-a2eb-bd893c97eac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/ng2-st-tbody-edit-delete/a/i</value>
      <webElementGuid>7c4b620f-4fad-42ac-ab49-47f9d86ba0f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
