<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search_1</name>
   <tag></tag>
   <elementGuidId>1d1f0e21-0a0a-4b6e-9fff-14cf5cb770dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnsearchView</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnsearchView']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c9397bb2-f2c8-4a0a-a474-12ba78627890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d40906c9-7c42-44f9-81f3-8f9a98d367cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-circle blue</value>
      <webElementGuid>b7c7142a-757d-4c4f-ac9c-c172259fc953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnsearchView</value>
      <webElementGuid>ee17acb6-13ef-47d8-bb1a-21a37a99665b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>searchReport('/accountingreport/searchlistentries/')</value>
      <webElementGuid>2c603890-e1d2-4861-aa74-57dbced80c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>ee29f597-dda0-444b-b9d5-3340e38f7685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnsearchView&quot;)</value>
      <webElementGuid>1f3b0cb3-d4b3-4023-b428-27231016c7ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnsearchView']</value>
      <webElementGuid>1626b540-b66f-4c21-9ba3-6e41ef8c57f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchformview']/div/div/div[5]/div/button</value>
      <webElementGuid>21a10036-3df4-4cbd-aaee-f4d7c8fa78a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ref No'])[1]/following::button[1]</value>
      <webElementGuid>68d1b985-d2b5-4dab-a37c-1369ddb93cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabang'])[1]/following::button[1]</value>
      <webElementGuid>3a261575-36dd-4581-ba4d-fa773a898c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jurnal No'])[1]/preceding::button[1]</value>
      <webElementGuid>53dec2ee-1ef5-4c95-8d24-62b0ff8b67e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ref No'])[2]/preceding::button[1]</value>
      <webElementGuid>b69c00ed-4ffa-4f5c-8531-5830e654417f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>28826246-e44f-430e-9d2d-7adcb4b418ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnsearchView' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>4de502d3-84e3-4136-a305-a1a67b86a42f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
