<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Akhir_datefinish</name>
   <tag></tag>
   <elementGuidId>a6c0c683-c7df-4b45-9405-80ff9d98191d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datefinish</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datefinish']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a980c85d-1728-493d-86e1-8fd6b4675652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-inline input-medium date-picker</value>
      <webElementGuid>ad83abf2-613e-435e-9f49-ba0f881aa488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datefinish</value>
      <webElementGuid>dc9b4089-e703-488d-a97b-94c8055710e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datefinish</value>
      <webElementGuid>cebdfe30-f748-4e79-8769-6b35fe7c7174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$(this).datepicker('show')</value>
      <webElementGuid>3aa542da-f218-4726-8b06-5a1f9216fcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e4eac23-9299-4104-9011-76f492d8da92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>04/07/2023</value>
      <webElementGuid>4a360c94-720c-412a-aae9-4f7a7a0223c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datefinish&quot;)</value>
      <webElementGuid>28452823-93ad-4c6d-a351-a3e108fa23d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datefinish']</value>
      <webElementGuid>583ef754-89cb-4d50-926a-fb1e9f861a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchformview']/div/div/div[2]/div/input</value>
      <webElementGuid>59cf458c-058e-45f3-bbe6-720c70319156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>b90c8f26-7472-458d-a60e-fa1f21931596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'datefinish' and @name = 'datefinish' and @type = 'text']</value>
      <webElementGuid>4c2371d1-79d9-4b4e-bf76-487e28812012</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
