<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Awal_datestart</name>
   <tag></tag>
   <elementGuidId>d3221083-ff42-401b-8443-260ec12f6589</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datestart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='datestart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e0822af-e4d6-4753-87ff-26658c11f614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-inline input-medium date-picker</value>
      <webElementGuid>325ffe1d-4920-4d65-980d-e42e58cfca78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datestart</value>
      <webElementGuid>86bdefc0-51e7-4c17-bcc3-8b1b86258ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datestart</value>
      <webElementGuid>952255ac-ba9b-4b59-a699-2500db615b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>$(this).datepicker('show')</value>
      <webElementGuid>e1fe6c6b-1674-48d1-b06f-abf3e13b9ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92dae465-7972-4932-8281-8af152a66eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>04/07/2023</value>
      <webElementGuid>1ab442f0-c9be-456e-9960-66eeb7afdbaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datestart&quot;)</value>
      <webElementGuid>5231af20-6bc2-4500-adeb-636dc8148895</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datestart']</value>
      <webElementGuid>613b5452-9895-4071-b995-616a77f31e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchformview']/div/div/div/div/input</value>
      <webElementGuid>c1f4672d-7d78-4987-a30f-1816c806d16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/input</value>
      <webElementGuid>e9a21101-4887-42bc-b5a8-1e0b761c48fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'datestart' and @name = 'datestart' and @type = 'text']</value>
      <webElementGuid>d53c0047-fbf4-4ecb-9366-e571757b2dee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
