<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Biasa_check_pilih_5</name>
   <tag></tag>
   <elementGuidId>3cb57fb6-4020-4a21-acdb-38b045a42887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#check_pilih_5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='check_pilih_5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b596455-e359-4376-a486-21848b82d50d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>88886fba-5cec-4662-916f-54ad5c063377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>check_pilih_5</value>
      <webElementGuid>3bf6964c-3570-4b1b-a6a9-d312dd7967b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check_pilih</value>
      <webElementGuid>897445a1-f21b-4513-8179-e78f4c1ea323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>checkedrekpilih(5)</value>
      <webElementGuid>b1508db6-0923-49ad-88e1-38541158e30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;check_pilih_5&quot;)</value>
      <webElementGuid>9de61fff-0293-410a-815a-15eb016ce12e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='check_pilih_5']</value>
      <webElementGuid>3d2f9b18-56e5-4e99-9f5b-e6242aac5893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblObjAcc']/tbody/tr[6]/td[5]/input</value>
      <webElementGuid>a5492d38-5d5c-4d44-861e-d6e18333f3ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[5]/input</value>
      <webElementGuid>1466f8f7-cfaa-4507-a442-10a33af8079f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'check_pilih_5']</value>
      <webElementGuid>912797cb-de01-42ab-a495-cebd2c827f00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
