<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Biasa_check_pilih_3</name>
   <tag></tag>
   <elementGuidId>735c9157-6cdd-482e-89a7-8009f4d4411c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#check_pilih_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='check_pilih_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c74dee5d-00cd-4efa-8a26-36e68a2f0369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8584ec9f-1aff-4495-96a1-66902a4dbc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>check_pilih_3</value>
      <webElementGuid>f5cd09f7-b989-496c-a938-605fc8f54245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check_pilih</value>
      <webElementGuid>8c74976f-3efe-427e-b22a-eb1e1f5d8387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>checkedrekpilih(3)</value>
      <webElementGuid>237a06cb-294d-4b0c-8766-abde8579947e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;check_pilih_3&quot;)</value>
      <webElementGuid>18ee8a78-0b29-4dd8-8bb6-3aad049febea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='check_pilih_3']</value>
      <webElementGuid>2d504905-fe5e-4fe6-bffa-48c95f4388a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblObjAcc']/tbody/tr[4]/td[5]/input</value>
      <webElementGuid>a057a211-03b5-4ce0-8af7-c335c806c8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/input</value>
      <webElementGuid>2960df75-086e-4216-996e-a74a491389f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'check_pilih_3']</value>
      <webElementGuid>3cbd3a94-0ac6-49d0-a81c-ca3996aa7a91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
