<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Otorisasi</name>
   <tag></tag>
   <elementGuidId>d8ea6f44-7d44-4330-ab01-d30cb285e0be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#blockui_sample_2_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='blockui_sample_2_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>758efeee-4a33-4234-8381-1619262ec238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>b6d5e1b4-5335-418e-bddf-ba5104ed29b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return view('/accountauth/detail/54c2002b-77d6-4602-b0ae-795904e0c704/')</value>
      <webElementGuid>1e97be7d-1dd3-412e-ac0e-bc9c0094ab8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn default btn-xs purple</value>
      <webElementGuid>2b1c3c65-3f9a-4026-ae54-1f1bbedf950d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>blockui_sample_2_1</value>
      <webElementGuid>d6611299-c22c-4537-80f9-eafac57d0c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                             Otorisasi
                                        </value>
      <webElementGuid>98784e1f-482d-462b-bb58-faf16db55b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TableBody&quot;)/tr[1]/td[5]/a[@id=&quot;blockui_sample_2_1&quot;]</value>
      <webElementGuid>286ee9f3-9c5f-4a96-9eb5-c61366be19a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='blockui_sample_2_1']</value>
      <webElementGuid>f6938df5-8f20-44ae-9fc0-3067d3919169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='TableBody']/tr/td[5]/a</value>
      <webElementGuid>e7348fff-542a-47a8-9342-5150541f7e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpanan Mobile - Anggota Koperasi'])[1]/following::a[1]</value>
      <webElementGuid>59186e62-3f66-4b6f-b70c-36bd108501ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrasi delapan'])[1]/following::a[1]</value>
      <webElementGuid>4608ac79-b90d-4868-ad55-162d610b44ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrasi delapan'])[2]/preceding::a[2]</value>
      <webElementGuid>f4d1de34-749a-4d8d-9661-d29cb5f4c92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[55]</value>
      <webElementGuid>97af6614-69c3-45f6-a9f1-3e2d1ca680cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>3de837f5-845d-4cbf-8bd9-dae1cac1b861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and @id = 'blockui_sample_2_1' and (text() = '
                                             Otorisasi
                                        ' or . = '
                                             Otorisasi
                                        ')]</value>
      <webElementGuid>543e0d89-00d7-4a34-a974-8a043b17ad6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
