<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Otorisasi</name>
   <tag></tag>
   <elementGuidId>2937d0c7-b581-4a19-ba8b-320421231956</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnsave</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnsave']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>562e84f7-669a-40ab-829d-21ed90452dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cbe3b26e-c714-48a2-8c4c-f55394d5dff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-circle</value>
      <webElementGuid>61b3c19b-3581-4b9d-9c33-4a0912277a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnsave</value>
      <webElementGuid>5845d4e2-efe8-4572-92b3-4bfbe0073190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>editDataRetail()</value>
      <webElementGuid>2425b385-8a9a-4097-97b8-4b93a8f7470a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Otorisasi</value>
      <webElementGuid>0d21aa83-3032-4b98-8939-d9693f8c2833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnsave&quot;)</value>
      <webElementGuid>0305425a-c219-47eb-98f0-1394ae9643b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnsave']</value>
      <webElementGuid>2d5c1fe0-bcd7-4926-bee9-8174da513a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='pageform']/div/div[2]/div/div/button[3]</value>
      <webElementGuid>552f1a1a-bf16-4ef0-8d9a-8a0ac6bd5e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::button[1]</value>
      <webElementGuid>fafff627-1d54-4226-b882-a3116a50d243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tolak'])[1]/following::button[2]</value>
      <webElementGuid>6a8777ab-020d-4c95-8d89-6c34340f4376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browse Customer'])[1]/preceding::button[2]</value>
      <webElementGuid>5d105b7c-be80-4a0c-a0b0-1daff287cc4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Customer'])[1]/preceding::button[2]</value>
      <webElementGuid>73d9e3ce-b55e-4725-9046-acca9be1c712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>8a3ce81f-7bd3-4599-bda5-a2ea9ae81350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnsave' and (text() = 'Otorisasi' or . = 'Otorisasi')]</value>
      <webElementGuid>620e1cc9-a5ce-4e46-b075-5778c5db24c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
