<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Actions_nb-edit</name>
   <tag></tag>
   <elementGuidId>558bd580-04f0-41f4-8b6f-792fe6439e72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.nb-edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng2-st-tbody-edit-delete/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4140651f-5736-4c32-9703-d16affb8a64f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nb-edit</value>
      <webElementGuid>44bbdda5-704c-4fc5-b900-e9fc41eb91a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;nb-theme-default    pace-done&quot;]/ngx-app[1]/ngx-pages[1]/ngx-sample-layout[1]/nb-layout[@class=&quot;window-mode with-scroll&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;columns&quot;]/nb-layout-column[@class=&quot;main-content&quot;]/ngx-master[@class=&quot;ng-star-inserted&quot;]/ngx-application-configuration[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/nb-card[1]/nb-card-body[1]/ng2-smart-table[1]/table[1]/tbody[1]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;ng2-smart-actions ng-star-inserted&quot;]/ng2-st-tbody-edit-delete[1]/a[@class=&quot;ng2-smart-action ng2-smart-action-edit-edit ng-star-inserted&quot;]/i[@class=&quot;nb-edit&quot;]</value>
      <webElementGuid>66d3547d-19db-40cc-87da-6caa11f95528</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng2-st-tbody-edit-delete/a/i</value>
      <webElementGuid>7ece74f5-2015-47d1-b108-fc6f7a2c775e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
